import Head from 'next/head'
import styled from 'styled-components'

const Main = styled.main`
  padding: 3rem;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>Content</Main>
    </>
  )
}
